CREATE TABLE BOOK
(
ISBN VARCHAR(50) NOT NULL,
BOOK_NAME VARCHAR(100) NOT NULL,
PRICE INT,
PRIMARY KEY (ISBN)
);


CREATE TABLE BOOK_STOCK
(
ISBN VARCHAR(50) NOT NULL,
STOCK INT NOT NULL,
PRIMARY KEY (ISBN),
CHECK (STOCK>=0)
);


CREATE TABLE ACCOUNT
(
USERID INT NOT NULL,
BALANCE INT NOT NULL,
PRIMARY KEY(USERID),
CHECK (BALANCE>=0)
);



INSERT INTO BOOK VALUES(0001,'The First Book',30);
INSERT INTO BOOK_STOCK VALUES(0001,10);
INSERT INTO ACCOUNT VALUES(101,20);
commit;


select * from BOOK;
select * from BOOK_STOCK;
select * from ACCOUNT;

DROP TABLE BOOK;
DROP TABLE BOOK_STOCK;
DROP TABLE ACCOUNT;
